export const CAFE_LIST_REQUEST = 'CAFE_LIST_REQUEST';
export const CAFE_LIST_SUCCESS = 'CAFE_LIST_SUCCESS';
export const CAFE_LIST_FAIL = 'CAFE_LIST_FAIL';

export const CAFE_DETAILS_REQUEST = 'CAFE_DETAILS_REQUEST';
export const CAFE_DETAILS_SUCCESS = 'CAFE_DETAILS_SUCCESS';
export const CAFE_DETAILS_FAIL = 'CAFE_DETAILS_FAIL';

export const CREATE_CAFE_REQUEST = 'CREATE_CAFE_REQUEST';
export const CREATE_CAFE_SUCCESS = 'CREATE_CAFE_SUCCESS';
export const CREATE_CAFE_FAIL = 'CREATE_CAFE_FAIL';

export const CAFE_DELETE_REQUEST = 'CAFE_DELETE_REQUEST';
export const CAFE_DELETE_SUCCESS = 'CAFE_DELETE_SUCCESS';
export const CAFE_DELETE_FAIL = 'CAFE_DELETE_FAIL';

export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL';